create table public."Customers" (
  "taxId" text not null,
  name text not null,
  site text null,
  segment text null,
  address_street text null,
  address_city text null,
  address_state text null,
  address_zip text null,
  updated_at timestamp with time zone not null default now(),
  constraint Customers_pkey primary key ("taxId")
) TABLESPACE pg_default;

create table public."Products" (
  id bigint generated by default as identity not null,
  name text not null,
  enabled boolean not null default true,
  category text not null,
  price numeric null default '0'::numeric,
  stock numeric null default '0'::numeric,
  updated_at timestamp with time zone not null default now(),
  constraint Products_pkey primary key (id)
) TABLESPACE pg_default;


INSERT INTO public."Customers" ("taxId", name, site, segment, address_street, address_city, address_state, address_zip) VALUES
('11.222.333/0001-44', 'Arena Sports Ltda', 'www.arenasports.com.br', 'Varejo', 'Av. Paulista, 1500', 'São Paulo', 'SP', '01310-100'),
('22.333.444/0001-55', 'ProFit Equipamentos S.A.', 'www.profitequipamentos.com.br', 'Atacado', 'Rua das Indústrias, 320', 'Campinas', 'SP', '13010-200'),
('33.444.555/0001-66', 'Sport Center Comércio Ltda', 'www.sportcenter.com.br', 'Varejo', 'Av. Beira Mar, 780', 'Florianópolis', 'SC', '88010-300'),
('44.555.666/0001-77', 'Olimpo Artigos Esportivos Ltda', 'www.olimpoesportes.com.br', 'Varejo', 'Rua XV de Novembro, 450', 'Curitiba', 'PR', '80020-310'),
('55.666.777/0001-88', 'MaxRun Distribuidora S.A.', 'www.maxrun.com.br', 'Distribuidor', 'Av. das Américas, 2200', 'Rio de Janeiro', 'RJ', '22640-100'),
('66.777.888/0001-99', 'FitLife Academia e Loja Ltda', 'www.fitlifeacademia.com.br', 'Academia', 'Rua Voluntários da Pátria, 900', 'Porto Alegre', 'RS', '90020-170'),
('77.888.999/0001-11', 'Esporte Total Comércio Ltda', 'www.esportetotal.com.br', 'Varejo', 'Av. Getúlio Vargas, 1100', 'Belo Horizonte', 'MG', '30112-020'),
('88.999.000/0001-22', 'TrailPro Outdoor Ltda', 'www.trailpro.com.br', 'Varejo', 'Rua da Consolação, 670', 'São Paulo', 'SP', '01301-000'),
('99.000.111/0001-33', 'AquaSport Natação e Mergulho Ltda', 'www.aquasport.com.br', 'Especializado', 'Av. Atlântica, 3400', 'Rio de Janeiro', 'RJ', '22070-001'),
('10.111.222/0001-44', 'Power Gym Suplementos Ltda', 'www.powergym.com.br', 'Nutrição Esportiva', 'Rua Oscar Freire, 220', 'São Paulo', 'SP', '01426-001'),
('11.222.444/0001-55', 'Velocidade Bikes e Acessórios Ltda', 'www.velocidadebikes.com.br', 'Especializado', 'Av. Independência, 540', 'Porto Alegre', 'RS', '90035-070'),
('12.333.555/0001-66', 'GolSport Futebol Ltda', 'www.golsport.com.br', 'Varejo', 'Rua Marechal Deodoro, 800', 'Curitiba', 'PR', '80010-010'),
('13.444.666/0001-77', 'Rede Esportiva Nacional S.A.', 'www.redeesportiva.com.br', 'Atacado', 'Av. Engenheiro Luís Carlos Berrini, 1500', 'São Paulo', 'SP', '04571-000'),
('14.555.777/0001-88', 'Decathlon Brasil Ltda', 'www.decathlon.com.br', 'Varejo', 'Av. das Nações Unidas, 3000', 'São Paulo', 'SP', '04578-000'),
('15.666.888/0001-99', 'Running Store Comércio Ltda', 'www.runningstore.com.br', 'Especializado', 'Rua Padre Chagas, 150', 'Porto Alegre', 'RS', '90570-080'),
('16.777.999/0001-00', 'Crossfit Box Equipamentos Ltda', 'www.crossfitbox.com.br', 'Academia', 'Av. Raja Gabaglia, 1200', 'Belo Horizonte', 'MG', '30350-540'),
('17.888.000/0001-11', 'SportMax Atacado e Varejo S.A.', 'www.sportmax.com.br', 'Atacado', 'Rua Voluntários da Pátria, 400', 'Manaus', 'AM', '69025-050'),
('18.999.111/0001-22', 'Surf & Skate Shop Ltda', 'www.surfskateshop.com.br', 'Varejo', 'Av. Boa Viagem, 2500', 'Recife', 'PE', '51011-000'),
('19.000.222/0001-33', 'Maratona Esportes Ltda', 'www.maratonaesportes.com.br', 'Varejo', 'Av. Afonso Pena, 3000', 'Belo Horizonte', 'MG', '30130-009'),
('20.111.333/0001-44', 'Champions Sports Club Ltda', 'www.championssports.com.br', 'Especializado', 'Rua Visconde de Pirajá, 550', 'Rio de Janeiro', 'RJ', '22410-002');

INSERT INTO public."Products" (name, enabled, category, price, stock) VALUES
-- Footwear
('Nike Air Max 270 Men''s Sneakers', true, 'Footwear', 599.90, 45),
('Adidas Ultraboost 22 Women''s Sneakers', true, 'Footwear', 749.90, 32),
('Adidas Predator Edge Men''s Soccer Cleats', true, 'Footwear', 499.90, 28),
('Puma RS-X Men''s Sneakers', true, 'Footwear', 429.90, 50),
('Asics Gel-Nimbus 24 Women''s Running Shoes', true, 'Footwear', 899.90, 18),
('New Balance 574 Unisex Sneakers', true, 'Footwear', 479.90, 40),
('Nike Mercurial Vapor 15 Men''s Soccer Cleats', true, 'Footwear', 649.90, 22),
('Under Armour HOVR Phantom Men''s Sneakers', true, 'Footwear', 559.90, 35),

-- Clothing
('Nike Dri-FIT Men''s Training T-Shirt', true, 'Clothing', 129.90, 120),
('Adidas Tiro 23 Men''s Shorts', true, 'Clothing', 149.90, 95),
('Puma Evostripe Women''s Leggings', true, 'Clothing', 189.90, 80),
('Under Armour Storm Men''s Jacket', true, 'Clothing', 349.90, 42),
('New Balance Women''s Tank Top', true, 'Clothing', 99.90, 110),
('Nike Pro Men''s Compression Pants', true, 'Clothing', 219.90, 65),
('Adidas Techfit Women''s Sports Bra', true, 'Clothing', 159.90, 75),
('Puma Essential Unisex Hoodie', true, 'Clothing', 279.90, 55),
('Speedo UV Men''s Swim Shorts', true, 'Clothing', 119.90, 88),
('Mizuno Dry Fit Men''s T-Shirt', true, 'Clothing', 109.90, 100),

-- Accessories
('Nike Brasilia 9.5 Unisex Backpack', true, 'Accessories', 299.90, 60),
('Under Armour 700ml Thermal Water Bottle', true, 'Accessories', 149.90, 90),
('Adidas Running Unisex Cap', true, 'Accessories', 89.90, 130),
('Nike Performance High-Cut Socks 3-Pack', true, 'Accessories', 79.90, 200),
('Oakley Holbrook Unisex Sunglasses', true, 'Accessories', 699.90, 25),
('Penalty Unisex Training Gloves', true, 'Accessories', 69.90, 150),
('Speedo Microfiber Sports Towel', true, 'Accessories', 59.90, 180),
('Garmin Forerunner 55 Unisex Smartwatch', true, 'Accessories', 1199.90, 15),
('JBL Endurance Run Unisex Earphones', true, 'Accessories', 199.90, 70),
('Salomon Unisex Hydration Belt', true, 'Accessories', 179.90, 38),

-- Equipment
('Adidas Al Rihla FIFA Soccer Ball', true, 'Equipment', 349.90, 30),
('Spalding NBA Official Basketball', true, 'Equipment', 299.90, 20),
('Wilson Blade 98 Adult Tennis Racket', true, 'Equipment', 1099.90, 12),
('Kikos F3i Exercise Bike', true, 'Equipment', 1899.90, 8),
('Movement E17 Pro Electric Treadmill', true, 'Equipment', 3499.90, 5),
('Rubber Dumbbells 5kg Pair', true, 'Equipment', 129.90, 60),
('Muvin Speed Jump Rope', true, 'Equipment', 59.90, 100),
('Acte Sports 5mm Yoga Mat', true, 'Equipment', 89.90, 85),
('Rubber Kettlebell 12kg', true, 'Equipment', 199.90, 40),
('Kikos 1.80m Barbell', true, 'Equipment', 249.90, 22),
('Resistance Bands Kit 5 Levels', true, 'Equipment', 79.90, 110),
('Speedo Kickboard Swimming Board', true, 'Equipment', 69.90, 55),

-- Swimming
('Speedo Biofuse 2.0 Swimming Goggles', true, 'Swimming', 149.90, 65),
('Speedo Unisex Silicone Swim Cap', true, 'Swimming', 39.90, 120),
('Speedo Endurance+ Women''s Swimsuit', true, 'Swimming', 189.90, 48),
('Speedo Men''s Swim Brief', true, 'Swimming', 79.90, 90),
('Speedo Biofuse Adult Swim Fins', true, 'Swimming', 129.90, 35),

-- Sports Nutrition
('Optimum Nutrition Gold Standard Whey 907g', true, 'Sports Nutrition', 189.90, 75),
('Integral Medica Creatine Monohydrate 300g', true, 'Sports Nutrition', 89.90, 95),
('Darkness Chocolate Protein Bar 90g', true, 'Sports Nutrition', 14.90, 300),
('Optimum Nutrition BCAA 2400 200 Capsules', true, 'Sports Nutrition', 119.90, 60),
('Gatorade Lemon Isotonic Drink 500ml', true, 'Sports Nutrition', 7.90, 500);